In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Data = pd.read_csv("/home/ahmed122/Personal/Hackathon/hackthon/data/final_vle_2.csv")

In [3]:
Data.head()

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,...,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,score_min,total_clicks,activity_diversity
0,0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,...,N,Pass,-159.0,NaN,82.0,85.0,5.0,78.0,934.0,6.0
1,1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,...,N,Pass,-53.0,NaN,66.4,70.0,5.0,60.0,1435.0,7.0
2,2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,...,Y,Withdrawn,-92.0,12.0,NaN,NaN,NaN,NaN,281.0,6.0
3,3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,...,N,Pass,-52.0,NaN,76.0,88.0,5.0,71.0,2158.0,8.0
4,4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,...,N,Pass,-176.0,NaN,54.4,75.0,5.0,30.0,1034.0,7.0

In [4]:
Data.shape

(32593, 21)

In [17]:
def calc_na_percentage(Data:pd.DataFrame) -> list:
    values = []
    for column in Data.columns:
        na = Data[column].isna().sum()/Data.shape[0]*100
        values.append(column)
        values.append(na)
    return values

In [12]:
# Dictionary to store each course DataFrame
dfs_by_course = {}

for course, group_df in Data.groupby("code_module"):
    dfs_by_course[course] = group_df.reset_index(drop=True)

# Example access:
df_AAA = dfs_by_course["AAA"]
df_BBB = dfs_by_course["BBB"]
df_CCC = dfs_by_course["CCC"]
df_DDD = dfs_by_course["DDD"]
df_EEE = dfs_by_course["EEE"]
df_FFF = dfs_by_course["FFF"]
df_GGG = dfs_by_course["GGG"]
print(dfs_by_course.keys())

dict_keys(['AAA', 'BBB', 'CCC', 'DDD', 'EEE', 'FFF', 'GGG'])

In [14]:
print(df_AAA.shape, df_BBB.shape,df_CCC.shape,df_DDD.shape,df_EEE.shape,df_FFF.shape,df_GGG.shape)

(748, 21) (7909, 21) (4434, 21) (6272, 21) (2934, 21) (7762, 21) (2534, 21)

In [15]:
df_AAA

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,...,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,score_min,total_clicks,activity_diversity
0,0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,...,N,Pass,-159.0,NaN,82.000000,85.0,5.0,78.0,934.0,6.0
1,1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,...,N,Pass,-53.0,NaN,66.400000,70.0,5.0,60.0,1435.0,7.0
2,2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,...,Y,Withdrawn,-92.0,12.0,NaN,NaN,NaN,NaN,281.0,6.0
3,3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,...,N,Pass,-52.0,NaN,76.000000,88.0,5.0,71.0,2158.0,8.0
4,4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,...,N,Pass,-176.0,NaN,54.400000,75.0,5.0,30.0,1034.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,743,AAA,2014J,2680312,M,Scotland,HE Qualification,90-100%,55<=,0,...,N,Pass,-44.0,NaN,78.800000,86.0,5.0,73.0,4966.0,7.0
744,744,AAA,2014J,2688166,M,Yorkshire Region,Lower Than A Level,40-50%,35-55,0,...,N,Pass,-56.0,NaN,59.500000,69.0,4.0,46.0,680.0,6.0
745,745,AAA,2014J,2690062,F,North Western Region,A Level or Equivalent,90-100%,35-55,0,...,N,Withdrawn,-25.0,32.0,58.000000,58.0,1.0,58.0,257.0,6.0
746,746,AAA,2014J,2692514,M,North Western Region,Lower Than A Level,0-10%,35-55,0,...,N,Pass,-44.0,NaN,78.200000,85.0,5.0,74.0,6661.0,6.0
747,747,AAA,2014J,2694788,F,South Region,A Level or Equivalent,70-80%,35-55,0,...,Y,Fail,-92.0,NaN,35.333333,51.0,3.0,20.0,100.0,5.0

In [16]:
df_AAA.info()

<class 'pandas.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 748 non-null    int64
 1   code_module           748 non-null    str
 2   code_presentation     748 non-null    str
 3   id_student            748 non-null    int64
 4   gender                748 non-null    str
 5   region                748 non-null    str
 6   highest_education     748 non-null    str
 7   imd_band              725 non-null    str
 8   age_band              748 non-null    str
 9   num_of_prev_attempts  748 non-null    int64
 10  studied_credits       748 non-null    int64
 11  disability            748 non-null    str
 12  final_result          748 non-null    str
 13  date_registration     748 non-null    float64
 14  date_unregistration   126 non-null    float64
 15  avg_score             704 non-null    float64
 16  max_score             704 non-null    float64
 17  num_submissions       705 non-null    float64
 18  score_min             704 non-null    float64
 19  total_clicks          735 non-null    float64
 20  activity_diversity    735 non-null    float64
dtypes: float64(8), int64(4), str(9)
memory usage: 166.8 KB

In [18]:
calc_na_percentage(df_AAA)

['index',
 np.float64(0.0),
 'code_module',
 np.float64(0.0),
 'code_presentation',
 np.float64(0.0),
 'id_student',
 np.float64(0.0),
 'gender',
 np.float64(0.0),
 'region',
 np.float64(0.0),
 'highest_education',
 np.float64(0.0),
 'imd_band',
 np.float64(3.074866310160428),
 'age_band',
 np.float64(0.0),
 'num_of_prev_attempts',
 np.float64(0.0),
 'studied_credits',
 np.float64(0.0),
 'disability',
 np.float64(0.0),
 'final_result',
 np.float64(0.0),
 'date_registration',
 np.float64(0.0),
 'date_unregistration',
 np.float64(83.15508021390374),
 'avg_score',
 np.float64(5.88235294117647),
 'max_score',
 np.float64(5.88235294117647),
 'num_submissions',
 np.float64(5.748663101604278),
 'score_min',
 np.float64(5.88235294117647),
 'total_clicks',
 np.float64(1.7379679144385027),
 'activity_diversity',
 np.float64(1.7379679144385027)]

In [29]:
def Year_and_semester_extractor(Data: pd.DataFrame):
    df = Data.copy()
    df["presentation_year"] = df["code_presentation"].str[:4].astype(int)
    df["presentation_semester"] = df["code_presentation"].str[-1]
    df.drop(["code_presentation"],axis=1,inplace=True)
    return df

In [30]:
df_AAA = Year_and_semester_extractor(df_AAA)
df_BBB = Year_and_semester_extractor(df_BBB)
df_CCC = Year_and_semester_extractor(df_CCC)
df_DDD = Year_and_semester_extractor(df_DDD)
df_EEE = Year_and_semester_extractor(df_EEE)
df_FFF = Year_and_semester_extractor(df_FFF)
df_GGG = Year_and_semester_extractor(df_GGG)

In [31]:
df_GGG

,index,code_module,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,date_registration,date_unregistration,avg_score,max_score,num_submissions,score_min,total_clicks,activity_diversity,presentation_year,presentation_semester
0,30059,GGG,24391,M,East Midlands Region,A Level or Equivalent,80-90%,0-35,0,30,...,-64.0,NaN,88.888889,100.0,9.0,80.0,712.0,7.0,2013,J
1,30060,GGG,26023,M,North Western Region,Lower Than A Level,10-20,35-55,0,30,...,-37.0,NaN,88.000000,100.0,9.0,53.0,786.0,7.0,2013,J
2,30061,GGG,32239,F,London Region,A Level or Equivalent,30-40%,0-35,0,30,...,-78.0,NaN,80.625000,100.0,8.0,55.0,620.0,6.0,2013,J
3,30062,GGG,35001,F,East Midlands Region,Lower Than A Level,70-80%,35-55,0,30,...,-27.0,NaN,75.000000,80.0,2.0,70.0,77.0,6.0,2013,J
4,30063,GGG,60405,F,Yorkshire Region,A Level or Equivalent,10-20,35-55,0,30,...,-123.0,NaN,88.666667,100.0,9.0,60.0,852.0,7.0,2013,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2529,32588,GGG,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,...,-4.0,NaN,NaN,NaN,NaN,NaN,41.0,4.0,2014,J
2530,32589,GGG,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,...,-23.0,NaN,88.111111,100.0,9.0,72.0,893.0,7.0,2014,J
2531,32590,GGG,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,...,-129.0,NaN,76.666667,100.0,9.0,60.0,312.0,6.0,2014,J
2532,32591,GGG,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,...,-49.0,101.0,91.500000,100.0,2.0,83.0,275.0,6.0,2014,J
2533,32592,GGG,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,...,-28.0,NaN,82.857143,100.0,7.0,60.0,616.0,6.0,2014,J