In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv("/home/ahmed122/Personal/Hackathon/hackthon/data/final_vle.csv")

In [3]:
Data.head()

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,total_clicks,activity_diversity
0,0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,-159.0,NaN,82.0,85.0,5.0,934.0,6.0
1,1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,-53.0,NaN,66.4,70.0,5.0,1435.0,7.0
2,2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,-92.0,12.0,NaN,NaN,NaN,281.0,6.0
3,3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,-52.0,NaN,76.0,88.0,5.0,2158.0,8.0
4,4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,-176.0,NaN,54.4,75.0,5.0,1034.0,7.0

In [4]:
Data.shape

(32593, 20)

In [5]:
import numpy as np

In [14]:
def calc_na_percentage(Data:pd.DataFrame) -> list:
    values = []
    for column in Data.columns:
        na = Data[column].isna().sum()/Data.shape[0]*100
        values.append(column)
        values.append(na)
    return values

In [15]:
calc_na_percentage(Data)

['index',
 np.float64(0.0),
 'code_module',
 np.float64(0.0),
 'code_presentation',
 np.float64(0.0),
 'id_student',
 np.float64(0.0),
 'gender',
 np.float64(0.0),
 'region',
 np.float64(0.0),
 'highest_education',
 np.float64(0.0),
 'imd_band',
 np.float64(3.408707391157611),
 'age_band',
 np.float64(0.0),
 'num_of_prev_attempts',
 np.float64(0.0),
 'studied_credits',
 np.float64(0.0),
 'disability',
 np.float64(0.0),
 'final_result',
 np.float64(0.0),
 'date_registration',
 np.float64(0.13806645598748196),
 'date_unregistration',
 np.float64(69.09765900653515),
 'avg_score',
 np.float64(20.78053569784923),
 'max_score',
 np.float64(20.78053569784923),
 'num_submissions',
 np.float64(20.709968398122296),
 'total_clicks',
 np.float64(10.324302764397263),
 'activity_diversity',
 np.float64(10.324302764397263)]

In [ ]:
Data['date_unregistration']= Data['date_unregistration'].fillna(0)

In [42]:
Data[(Data['avg_score'].isna()) & (Data['final_result']=='Pass')]

Empty DataFrame
Columns: [index, code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, final_result, date_registration, date_unregistration, avg_score, max_score, num_submissions, total_clicks, activity_diversity]
Index: []

In [40]:
Data = Data[~((Data['final_result'].isin(['Pass'])) & (Data['avg_score'].isna())) ]

In [43]:
Data[(Data['avg_score'].isna()) & (Data['final_result']=='Pass')]

Empty DataFrame
Columns: [index, code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, final_result, date_registration, date_unregistration, avg_score, max_score, num_submissions, total_clicks, activity_diversity]
Index: []

In [50]:
Data[(Data['final_result']=='Withdrawn')&(Data['date_unregistration']<=60)]

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,total_clicks,activity_diversity
2,2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,-92.0,12.0,NaN,NaN,NaN,281.0,6.0
44,44,AAA,2013J,135335,F,East Anglian Region,Lower Than A Level,20-30%,0-35,0,180,N,Withdrawn,-29.0,30.0,NaN,NaN,NaN,57.0,3.0
54,54,AAA,2013J,147793,F,North Region,Lower Than A Level,80-90%,0-35,0,90,N,Withdrawn,-138.0,58.0,52.0,52.0,1.0,155.0,5.0
72,72,AAA,2013J,181316,F,South West Region,A Level or Equivalent,80-90%,35-55,0,120,N,Withdrawn,-39.0,60.0,76.0,76.0,1.0,487.0,8.0
79,79,AAA,2013J,188278,M,Yorkshire Region,A Level or Equivalent,70-80%,35-55,0,120,N,Withdrawn,-57.0,60.0,76.0,76.0,1.0,1434.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32523,32523,GGG,2014J,695143,F,South West Region,Lower Than A Level,0-10%,35-55,0,90,Y,Withdrawn,3.0,37.0,NaN,NaN,NaN,5.0,3.0
32541,32541,GGG,2014J,697364,F,Ireland,Lower Than A Level,30-40%,0-35,0,30,N,Withdrawn,3.0,25.0,NaN,NaN,NaN,56.0,6.0
32570,32570,GGG,2014J,2239862,M,North Western Region,Lower Than A Level,50-60%,35-55,0,30,N,Withdrawn,-126.0,-43.0,NaN,NaN,NaN,NaN,NaN
32576,32576,GGG,2014J,2338614,F,Scotland,A Level or Equivalent,0-10%,35-55,0,30,Y,Withdrawn,-23.0,58.0,NaN,NaN,NaN,51.0,5.0
32586,32586,GGG,2014J,2608143,M,East Midlands Region,HE Qualification,60-70%,35-55,0,30,N,Withdrawn,-45.0,48.0,NaN,NaN,NaN,37.0,5.0

In [28]:
Data_tested = pd.read_csv("/home/ahmed122/Personal/Hackathon/hackthon/data/studentInfo.csv")

In [30]:
Data_tested[Data_tested['id_student']==1777834]

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
12893,CCC,2014J,1777834,F,East Anglian Region,A Level or Equivalent,80-90%,35-55,0,60,N,Pass